SELECT TOP (1000) [continent]
      ,[location]
      ,[date]
      ,[population]
      ,[new_vaccinations]
      ,[rollingpeoplevaccinated]
  FROM [CovidAnalysis].[dbo].[PercentPopulationVaccinated]
